version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - PORT_BACKEND=5003
