# Generated by Django 4.2.2 on 2023-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('profit_or_loss', models.IntegerField()),
                ('assets_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountingProviderBalanceSheet',
            fields=[
                ('accounting_provider', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('balance_sheet', models.ManyToManyField(to='biz_loan.report')),
            ],
        ),
    ]
